Update docker-publish.yml

diff --git a/.github/workflows/docker-publish.yml b/.github/workflows/docker-publish.yml
--- a/.github/workflows/docker-publish.yml
+++ b/.github/workflows/docker-publish.yml
@@ -37,6 +37,15 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v4
 
+      - name: Validate presence of cert.pfx
+        run: ls -R src/Fiap.McTech.Api/
+      - name: Ensure cert.pfx exists
+        run: |
+          if [ ! -f src/Fiap.McTech.Api/cert.pfx ]; then
+            echo "cert.pfx not found"
+            exit 1
+          fi
+
       # Install the cosign tool except on PR
       # https://github.com/sigstore/cosign-installer
       - name: Install cosign
